### ISSUE TITLE
[BUG] Settings command doesn't work

### ISSUE THREAD

**Issue by GamingGeek** [EnderDev/Ender#2]
**Describe the bug**
The settings command doesn't work

**To Reproduce**
1. type !settings

**Expected behavior**
A list of settings and values

**Screenshots**
https://join-the.gaminggeek.club/images/h0wrtvxs.png

**Important information (please enter this or your issue will be void)**

Guild ID: 564052798044504084
Your ID: 287698408855044097
Command you ran: !settings
Error: ```TypeError: Cannot read property 'replace' of null```

**Additional context**
error code: 289253051664136060

**Comment by EnderDev** [comment]
Hi, I am on this issue right now. If you could open a PR that would be great.
